apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "restaurant-watcher.name" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "restaurant-watcher.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
